{"uuid": "9b92fe15-cd3d-4140-b064-1ba48c539503", "children": ["9539685e-733e-4c01-b5c3-eadf9d153fbe"], "befores": [{"name": "app", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: no chrome binary at /usr/bin/google-chrome\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x01407413+2389011]\n\tOrdinal0 [0x01399F61+1941345]\n\tOrdinal0 [0x0128C658+837208]\n\tOrdinal0 [0x012A76A3+947875]\n\tOrdinal0 [0x012A5C51+941137]\n\tOrdinal0 [0x012D8C80+1150080]\n\tOrdinal0 [0x012D88DA+1149146]\n\tOrdinal0 [0x012D3F66+1130342]\n\tOrdinal0 [0x012AE546+976198]\n\tOrdinal0 [0x012AF456+980054]\n\tGetHandleVerifier [0x015B9632+1727522]\n\tGetHandleVerifier [0x0166BA4D+2457661]\n\tGetHandleVerifier [0x0149EB81+569713]\n\tGetHandleVerifier [0x0149DD76+566118]\n\tOrdinal0 [0x013A0B2B+1968939]\n\tOrdinal0 [0x013A5988+1989000]\n\tOrdinal0 [0x013A5A75+1989237]\n\tOrdinal0 [0x013AECB1+2026673]\n\tBaseThreadInitThunk [0x75EC62C4+36]\n\tRtlSubscribeWnfStateChangeNotification [0x77A80F79+1081]\n\tRtlSubscribeWnfStateChangeNotification [0x77A80F44+1028]\n\n", "trace": "  File \"c:\\python_project\\sotka_auto\\venv\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\python_project\\sotka_auto\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\python_project\\sotka_auto\\venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Python_project\\Sotka_auto\\conftest.py\", line 8, in app\n    fixture = Application()\n  File \"C:\\Python_project\\Sotka_auto\\pages\\application.py\", line 39, in __init__\n    self.wd = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=self.options)\n  File \"c:\\python_project\\sotka_auto\\venv\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"c:\\python_project\\sotka_auto\\venv\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 93, in __init__\n    RemoteWebDriver.__init__(\n  File \"c:\\python_project\\sotka_auto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\python_project\\sotka_auto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 359, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"c:\\python_project\\sotka_auto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\python_project\\sotka_auto\\venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1651306230768, "stop": 1651306233575}], "start": 1651306230768, "stop": 1651306233807}